version: '3.1'
services:
  ###################
  # Zookeeper
  # https://github.com/31z4/zookeeper-docker
  ###################

  zookeper:
    image: zookeeper:latest
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888
  ###################
  # Druid
  ###################
  docker-druid:
    build: druid/
    container_name: docker-druid
    ports:
      - 8081:8081
      - 8082:8082
  ######################
  # Superset
  # https://github.com/tylerFowler/docker-superset
  ######################
  docker-superset:
    build: superset/
    container_name: docker-superset
    ports:
      - 8088:8088
    depends_on:
      - docker-druid
    links:
      - docker-druid:docker-druid
